
menues:
  memueID: UID
    docID: string
    imageURL: string
    name: string
    plice: number
    category: string
    detailImageCount: number
    createdAt: timestamp
    updatedAt: timestamp

    imageURLs: docID
      docID: string # ○○○ - ○○○
      imageName: string
      imageURL: string
      createdAt: timestamp
      updatedAt: timestamp

  categories: UID
    docID: number
    categoryName: string
    createdAt: timestamp


users:
  userID: liffID
    - userName: string
